import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const typesPath = resolve(process.cwd(), 'src/types/index.ts');

test('Shop interface uses canonical camelCase contract fields only', async () => {
  const source = await readFile(typesPath, 'utf8');

  assert.match(source, /mqttSecret\?: string;/);
  assert.match(source, /expireDate\?: string;/);
  assert.match(source, /commissionType\?: \"per_order\" \| \"percentage\";/);
  assert.match(source, /commissionValue\?: number;/);
  assert.match(source, /lastPaidMonth\?: string;/);
  assert.match(source, /tableConfig\?: string;/);
  assert.match(source, /enableDelivery\?: number;/);
  assert.match(source, /enableDineIn\?: number;/);
  assert.match(source, /dineInBillingStartAt\?: string;/);
  assert.match(source, /dineInExpiresAt\?: string;/);
  assert.match(source, /dineInGraceUntil\?: string;/);
  assert.match(source, /dineInDisabledAt\?: string;/);
  assert.match(source, /dineInStopReason\?: \"manual\" \| \"auto_expired\";/);
  assert.match(source, /enableReservation\?: number;/);
  assert.match(source, /billingPlanType\?: \"subscription\" \| \"business\";/);
  assert.match(source, /billingBalanceRsd\?: number;/);
  assert.match(source, /deliveryChargeRsd\?: number;/);
  assert.match(source, /deliveryLocked\?: boolean;/);
  assert.match(source, /deliveryLockReason\?: string;/);
  assert.match(source, /ownerUserId\?: number;/);
  assert.match(source, /deliveryFeeSettings\?: string;/);
  assert.match(source, /deliveryType\?: \"merchant\" \| \"platform\";/);

  assert.doesNotMatch(source, /mqtt_secret\?: string;/);
  assert.doesNotMatch(source, /expire_date\?: string;/);
  assert.doesNotMatch(source, /commission_type\?:/);
  assert.doesNotMatch(source, /commission_value\?:/);
  assert.doesNotMatch(source, /last_paid_month\?:/);
  assert.doesNotMatch(source, /table_config\?:/);
  assert.doesNotMatch(source, /enable_delivery\?:/);
  assert.doesNotMatch(source, /enable_dine_in\?:/);
  assert.doesNotMatch(source, /dine_in_billing_start_at\?:/);
  assert.doesNotMatch(source, /dine_in_expires_at\?:/);
  assert.doesNotMatch(source, /dine_in_grace_until\?:/);
  assert.doesNotMatch(source, /dine_in_disabled_at\?:/);
  assert.doesNotMatch(source, /dine_in_stop_reason\?:/);
  assert.doesNotMatch(source, /enable_reservation\?:/);
  assert.doesNotMatch(source, /billing_plan_type\?:/);
  assert.doesNotMatch(source, /billing_balance_rsd\?:/);
  assert.doesNotMatch(source, /delivery_charge_rsd\?:/);
  assert.doesNotMatch(source, /delivery_locked\?:/);
  assert.doesNotMatch(source, /delivery_lock_reason\?:/);
  assert.doesNotMatch(source, /owner_user_id\?:/);
  assert.doesNotMatch(source, /delivery_fee_settings\?:/);
  assert.doesNotMatch(source, /delivery_type\?:/);
});

test('Order interface uses canonical camelCase contract fields only', async () => {
  const source = await readFile(typesPath, 'utf8');

  assert.match(source, /orderNo: string;/);
  assert.match(source, /restaurantId: number;/);
  assert.match(source, /shopName\?: string;/);
  assert.match(source, /shopSlug\?: string;/);
  assert.match(source, /restaurantName\?: string;/);
  assert.match(source, /restaurantSlug\?: string;/);
  assert.match(source, /userPoints\?: number;/);
  assert.match(source, /pointsBalance\?: number;/);
  assert.match(source, /isVip\?: boolean \| number \| string;/);
  assert.match(source, /vipLevel\?: string;/);
  assert.match(source, /tableInfo\?: string;/);
  assert.match(source, /totalAmount: number;/);
  assert.match(source, /itemsJson: string;/);
  assert.match(source, /originalItemsJson\?: string;/);
  assert.match(source, /remarksJson\?: string;/);
  assert.match(source, /userPhone\?: string;/);
  assert.match(source, /scheduledFor\?: string;/);
  assert.match(source, /createdAt: string;/);
  assert.match(source, /updatedAt\?: string;/);
  assert.match(source, /isDeleted\?: number;/);
  assert.match(source, /deletedAt\?: string;/);
  assert.match(source, /archivedAt\?: string;/);
  assert.match(source, /paidAt\?: string;/);
  assert.match(source, /courierName\?: string;/);
  assert.match(source, /courierPhone\?: string;/);
  assert.match(source, /pickupEtaMinutes\?: number;/);
  assert.match(source, /pickupReadyAt\?: string;/);
  assert.match(source, /riderBroadcastedAt\?: string;/);
  assert.match(source, /riderRemindCount\?: number;/);
  assert.match(source, /riderLastRemindedAt\?: string;/);
  assert.match(source, /riderContactAttemptedAt\?: string;/);
  assert.match(source, /modificationCount\?: number;/);
  assert.match(source, /deliveryFeeStatus\?: \"pending\" \| \"paid\";/);
  assert.match(source, /allowAdd\?: number;/);

  assert.doesNotMatch(source, /order_no: string;/);
  assert.doesNotMatch(source, /restaurant_id: number;/);
  assert.doesNotMatch(source, /shop_name\?:/);
  assert.doesNotMatch(source, /shop_slug\?:/);
  assert.doesNotMatch(source, /restaurant_name\?:/);
  assert.doesNotMatch(source, /restaurant_slug\?:/);
  assert.doesNotMatch(source, /user_points\?:/);
  assert.doesNotMatch(source, /points_balance\?:/);
  assert.doesNotMatch(source, /is_vip\?:/);
  assert.doesNotMatch(source, /vip_level\?:/);
  assert.doesNotMatch(source, /table_info\?:/);
  assert.doesNotMatch(source, /total_amount: number;/);
  assert.doesNotMatch(source, /items_json: string;/);
  assert.doesNotMatch(source, /original_items_json\?:/);
  assert.doesNotMatch(source, /remarks_json\?:/);
  assert.doesNotMatch(source, /user_phone\?:/);
  assert.doesNotMatch(source, /scheduled_for\?:/);
  assert.doesNotMatch(source, /created_at: string;/);
  assert.doesNotMatch(source, /updated_at\?:/);
  assert.doesNotMatch(source, /is_deleted\?:/);
  assert.doesNotMatch(source, /deleted_at\?:/);
  assert.doesNotMatch(source, /archived_at\?:/);
  assert.doesNotMatch(source, /paid_at\?:/);
  assert.doesNotMatch(source, /courier_name\?:/);
  assert.doesNotMatch(source, /courier_phone\?:/);
  assert.doesNotMatch(source, /pickup_eta_minutes\?:/);
  assert.doesNotMatch(source, /pickup_ready_at\?:/);
  assert.doesNotMatch(source, /rider_broadcasted_at\?:/);
  assert.doesNotMatch(source, /rider_remind_count\?:/);
  assert.doesNotMatch(source, /rider_last_reminded_at\?:/);
  assert.doesNotMatch(source, /rider_contact_attempted_at\?:/);
  assert.doesNotMatch(source, /modification_count\?:/);
  assert.doesNotMatch(source, /delivery_fee_status\?:/);
  assert.doesNotMatch(source, /allow_add\?:/);
});
