import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const pagePath = resolve(process.cwd(), 'src/pages/rider/dashboard.astro');

test('rider dashboard source uses canonical rider and order fields', async () => {
  const source = await readFile(pagePath, 'utf8');

  assert.match(source, /const orderNo = String\(safeOrder\.orderNo \|\| ''\)\.trim\(\);/);
  assert.match(source, /const restaurantId = String\(safeOrder\.shopSlug \|\| safeOrder\.restaurantSlug \|\| safeOrder\.restaurantId \|\| safeOrder\.shopId \|\| ''\)\.trim\(\);/);
  assert.match(source, /const bound = String\(rider\.telegramChatId \|\| ''\)\.trim\(\) !== '' && rider\.telegramChatId !== '__pending_refresh__';/);
  assert.match(source, /getRiderTelegramBindingCopy\(bound \? rider : \{ telegramChatId: '' \}\)/);
  assert.match(source, /telegramChatId: rider\.telegramChatId \|\| '__pending_refresh__',/);
  assert.match(source, /const bindLink = String\(bindState\.httpsUrl \|\| bindState\.tgUrl \|\| ''\)\.trim\(\);/);
  assert.match(source, /const showFallbackActions = !bound && bindState\.ready;/);
  assert.match(source, /<a id="bind-telegram-link" class="btn-action btn-map" target="_blank" rel="noreferrer">重新打开 Telegram<\/a>/);
  assert.match(source, /<button id="copy-telegram-bind-link-btn" class="btn-action" type="button">复制绑定链接<\/button>/);
  assert.match(source, /<button id="copy-telegram-bind-command-btn" class="btn-action" type="button">复制绑定命令<\/button>/);
  assert.match(source, /<button id="unbind-telegram-btn" class="btn-action" type="button">解除 Telegram 绑定<\/button>/);
  assert.match(source, /if \(unbindBtn\) unbindBtn\.addEventListener\('click', unbindTelegram\);/);
  assert.match(source, /if \(!confirm\('确认解除 Telegram 绑定？'\)\) return;/);
  assert.match(source, /async function unbindTelegram\(\) \{/);
  assert.match(source, /const res = await fetch\('\/api\/rider\/telegram\/unbind', \{/);
  assert.match(source, /body: JSON\.stringify\(\{ riderId: rider\.id, riderPhone: rider\.phone, riderStatus: rider\.status \}\),/);
  assert.match(source, /telegramChatId: ''/);
  assert.match(source, /bindState = \{ httpsUrl: '', tgUrl: '', startCommand: '', ready: false \};/);
  assert.match(source, /alert\('已解除 Telegram 绑定'\);/);
  assert.match(source, /<div class="telegram-binding-tip">如果 Telegram 里只出现普通 \/start，请点“复制绑定命令”后直接发送给机器人。<\/div>/);
  assert.match(source, /bindLinkEl\.href = bindLink;/);
  assert.match(source, /await navigator\.clipboard\.writeText\(bindLink\);/);
  assert.match(source, /const bindCommand = String\(bindState\.startCommand \|\| ''\)\.trim\(\);/);
  assert.match(source, /await navigator\.clipboard\.writeText\(bindCommand\);/);
  assert.match(source, /const statusRes = await fetch\(`\/api\/rider\/orders\?phone=\$\{encodeURIComponent\(rider\.phone \|\| ''\)\}&view=active`\);/);
  assert.match(source, /refreshRiderSessionFromPayload\(statusData\);/);
  assert.match(source, /telegramBound = false;/);
  assert.match(source, /if \(bindState\.tgUrl\) location\.href = bindState\.tgUrl;/);
  assert.match(source, /const items = parseItems\(o\.itemsJson\);/);
  assert.match(source, /const address = o\.tableInfo \|\| '';/);
  assert.match(source, /const phone = o\.userPhone \|\| '';/);
  assert.match(source, /const awaitingOrders = myOrders\.filter\(\(o\) => o\.status === 'awaiting_courier'\);/);
  assert.match(source, /const deliveringOrders = myOrders\.filter\(\(o\) => o\.status === 'delivering' && String\(o\.courierPhone \|\| ''\)\.trim\(\) === String\(rider\?\.phone \|\| ''\)\.trim\(\)\);/);
  assert.match(source, /poolTitle\.textContent = '待接单池';/);
  assert.match(source, /mineTitle\.textContent = '我的配送';/);
  assert.match(source, /const etaMinutes = Number\(o\.pickupEtaMinutes \|\| 0\);/);
  assert.match(source, /const error = String\(data\.error \|\| 'load_orders_failed'\);/);
  assert.match(source, /const failed = document\.createElement\('div'\);/);
  assert.match(source, /failed\.className = 'empty-tip';/);
  assert.match(source, /failed\.textContent = `加载失败: \$\{error\}`;/);
  assert.match(source, /container\.replaceChildren\(failed\);/);
  assert.match(source, /orderNo\.textContent = `#\$\{String\(o\.orderNo \|\| ''\)\.slice\(-4\)\}`;/);
  assert.match(source, /orderTime\.textContent = String\(o\.createdAt \|\| ''\)\.slice\(11, 16\);/);
  assert.match(source, /shop\.textContent = o\.shopName \|\| 'Shop';/);
  assert.match(source, /total\.textContent = `\$\{o\.totalAmount \|\| 0\} RSD`;/);
  assert.match(source, /status\.textContent = getAdminDispatchStatusCopy\(o\.status\);/);
  assert.match(source, /import \{[^}]*getAdminDispatchStatusCopy[^}]*\} from '\.\.\/\.\.\/lib\/rider-dispatch\.ts';/);
  assert.match(source, /String\(o\.courierPhone \|\| ''\)\.trim\(\) === String\(rider\?\.phone \|\| ''\)\.trim\(\)/);

  assert.doesNotMatch(source, /status\.textContent = o\.status;/);
  assert.match(source, /courierPhone: rider\.phone,/);
  assert.match(source, /courierName: rider\.name, courierPhone: rider\.phone/);

  assert.doesNotMatch(source, /order_no/);
  assert.doesNotMatch(source, /telegram_chat_id/);
  assert.doesNotMatch(source, /items_json/);
  assert.doesNotMatch(source, /table_info/);
  assert.doesNotMatch(source, /user_phone/);
  assert.doesNotMatch(source, /pickup_eta_minutes/);
  assert.doesNotMatch(source, /created_at/);
  assert.doesNotMatch(source, /shop_name/);
  assert.doesNotMatch(source, /total_amount/);
  assert.doesNotMatch(source, /courier_phone/);
  assert.doesNotMatch(source, /courier_name/);
});
