import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const pagePath = resolve(process.cwd(), 'src/pages/rider/dashboard.astro');

test('rider dashboard source uses canonical rider and order fields', async () => {
  const source = await readFile(pagePath, 'utf8');

  assert.match(source, /const orderNo = String\(safeOrder\.orderNo \|\| ''\)\.trim\(\);/);
  assert.match(source, /const restaurantId = String\(safeOrder\.shopSlug \|\| safeOrder\.restaurantSlug \|\| safeOrder\.restaurantId \|\| safeOrder\.shopId \|\| ''\)\.trim\(\);/);
  assert.match(source, /const bound = String\(rider\.telegramChatId \|\| ''\)\.trim\(\) !== '';/);
  assert.match(source, /getRiderTelegramBindingCopy\(bound \? rider : \{ telegramChatId: '' \}\)/);
  assert.match(source, /telegramChatId: rider\.telegramChatId \|\| '__bound__',/);
  assert.match(source, /const bindLink = String\(bindState\.httpsUrl \|\| bindState\.tgUrl \|\| ''\)\.trim\(\);/);
  assert.match(source, /const showFallbackActions = !bound && bindState\.ready;/);
  assert.match(source, /<div class="telegram-binding-steps-title">绑定步骤<\/div>/);
  assert.match(source, /<ol class="telegram-binding-steps"><li>先点“打开 Telegram”<\/li><li>如果 Telegram 聊天页是空白，再点“复制绑定命令”并发送给机器人<\/li><li>发送成功后回到此页查看状态<\/li><\/ol>/);
  assert.match(source, /<a id="bind-telegram-link" class="btn-action btn-map" target="_blank" rel="noreferrer">打开 Telegram<\/a>/);
  assert.match(source, /<button id="copy-telegram-bind-link-btn" class="btn-action" type="button">复制绑定链接<\/button>/);
  assert.match(source, /<button id="copy-telegram-bind-command-btn" class="btn-action" type="button">复制绑定命令<\/button>/);
  assert.match(source, /<button id="unbind-telegram-btn" class="btn-action" type="button">解除 Telegram 绑定<\/button>/);
  assert.match(source, /if \(unbindBtn\) unbindBtn\.addEventListener\('click', unbindTelegram\);/);
  assert.match(source, /if \(!confirm\('确认解除 Telegram 绑定？'\)\) return;/);
  assert.match(source, /async function unbindTelegram\(\) \{/);
  assert.match(source, /\.order-list \{ padding: 15px; padding-bottom: 80px; min-height: calc\(100vh - 160px\); overflow-y: auto; -webkit-overflow-scrolling: touch; \}/);
  assert.match(source, /const decline = document\.createElement\('button'\);/);
  assert.match(source, /decline\.type = 'button';/);
  assert.match(source, /decline\.className = 'btn-action';/);
  assert.match(source, /decline\.textContent = '暂不接单';/);
  assert.match(source, /decline\.addEventListener\('click', \(\) => window\.declineOrder\(o\.id\)\);/);
  assert.match(source, /window\.declineOrder = async function\(id\) \{/);
  assert.match(source, /const target = allOrders\.find\(\(item\) => String\(item\?\.id \|\| ''\)\.trim\(\) === String\(id \|\| ''\)\.trim\(\)\);/);
  assert.match(source, /const nextRemarks = buildDispatchMetaRemarks\(target\.remarksJson \|\| target\.remarks_json, \{/);
  assert.match(source, /action: 'declined',/);
  assert.match(source, /status: 'awaiting_courier',/);
  assert.match(source, /expected_current_status: 'awaiting_courier',/);
  assert.match(source, /remarks_json: JSON\.stringify\(nextRemarks\),/);
  assert.match(source, /await fetch\('\/api\/order\/update_status', \{/);
  assert.match(source, /loadOrders\(\);/);
  assert.match(source, /const res = await fetch\('\/api\/rider\/telegram\/unbind', \{/);
  assert.match(source, /body: JSON\.stringify\(\{ riderId: rider\.id, riderPhone: rider\.phone, riderStatus: rider\.status \}\),/);
  assert.match(source, /telegramChatId: ''/);
  assert.match(source, /bindState = \{ httpsUrl: '', tgUrl: '', startCommand: '', ready: false \};/);
  assert.match(source, /alert\('已解除 Telegram 绑定'\);/);
  assert.match(source, /<div class="telegram-binding-tip">如果 Telegram 里只出现普通 \/start，请点“复制绑定命令”后直接发送给机器人。<\/div>/);
  assert.match(source, /bindLinkEl\.href = bindLink;/);
  assert.match(source, /await navigator\.clipboard\.writeText\(bindLink\);/);
  assert.match(source, /const bindCommand = String\(bindState\.startCommand \|\| ''\)\.trim\(\);/);
  assert.match(source, /await navigator\.clipboard\.writeText\(bindCommand\);/);
  assert.match(source, /const statusRes = await fetch\(`\/api\/rider\/status\?phone=\$\{encodeURIComponent\(rider\.phone \|\| ''\)\}`\);/);
  assert.match(source, /const next = normalizeRiderSession\(statusData\.rider \|\| statusData\);/);
  assert.match(source, /persistRiderSession\(next\);/);
  assert.match(source, /async function handlePageWake\(\) \{/);
  assert.match(source, /await refreshTelegramBindingStatus\(\);/);
  assert.match(source, /await loadOrders\(\);/);
  assert.match(source, /async function handleVisibilityChange\(\) \{/);
  assert.match(source, /if \(!document\.hidden\) \{/);
  assert.match(source, /telegramBound = false;/);
  assert.doesNotMatch(source, /location\.href = bindState\.(httpsUrl|tgUrl);/);
  assert.match(source, /const items = parseItems\(o\.itemsJson\);/);
  assert.match(source, /const address = o\.tableInfo \|\| '';/);
  assert.match(source, /const phone = o\.userPhone \|\| '';/);
  assert.match(source, /const activeOrders = filterRiderDashboardOrders\(myOrders, rider\?\.phone, 'active'\);/);
  assert.match(source, /const awaitingOrders = activeOrders\.filter\(\(o\) => o\.status === 'awaiting_courier'\);/);
  assert.match(source, /isRiderDeliveringOrder/);
  assert.match(source, /const deliveringOrders = activeOrders\.filter\(\(o\) => isRiderDeliveringOrder\(o\.status\)\);/);
  assert.doesNotMatch(source, /const deliveringOrders = activeOrders\.filter\(\(o\) => o\.status === 'delivering' \|\| o\.status === 'picked_up'\);/);
  assert.match(source, /poolTitle\.textContent = '待接单池';/);
  assert.match(source, /mineTitle\.textContent = '我的配送';/);
  assert.match(source, /const actionFlags = getRiderActionFlags\(o, rider\?\.phone\);/);
  assert.match(source, /if \(actionFlags\.canPickUp\) \{/);
  assert.match(source, /complete\.textContent = '✅ 已取餐';/);
  assert.match(source, /complete\.addEventListener\('click', \(\) => window\.pickUpOrder\(o\.id\)\);/);
  assert.match(source, /if \(actionFlags\.canComplete\) \{/);
  assert.match(source, /complete\.textContent = '✅ 已送达';/);
  assert.match(source, /complete\.addEventListener\('click', \(\) => window\.completeOrder\(o\.id\)\);/);
  assert.match(source, /window\.pickUpOrder = async function\(id\) \{/);
  assert.match(source, /if \(!confirm\('确认已取餐，开始配送？'\)\) return;/);
  assert.match(source, /expected_current_status: 'delivering',/);
  assert.match(source, /status: 'picked_up',/);
  assert.match(source, /const etaMinutes = Number\(o\.pickupEtaMinutes \|\| 0\);/);
  assert.match(source, /const dispatchMeta = readDispatchMetaFromRemarks\(o\.remarksJson \|\| o\.remarks_json\);/);
  assert.match(source, /const actionState = getRiderDispatchState\(o, dispatchMeta, rider\?\.id\);/);
  assert.match(source, /const invalidReason = String\(actionState\.invalidReason \|\| ''\)\.trim\(\);/);
  assert.match(source, /invalidReason === '已改派' \|\| invalidReason === '接单超时'/);
  assert.match(source, /button\.disabled = true;/);
  assert.match(source, /button\.classList\.add\('btn-disabled'\);/);
  assert.match(source, /button\.textContent = actionState\.invalidReason;/);
  assert.match(source, /const error = String\(data\.error \|\| 'load_orders_failed'\);/);
  assert.match(source, /const failed = document\.createElement\('div'\);/);
  assert.match(source, /failed\.className = 'empty-tip';/);
  assert.match(source, /failed\.textContent = `加载失败: \$\{error\}`;/);
  assert.match(source, /container\.replaceChildren\(failed\);/);
  assert.match(source, /orderNo\.textContent = `#\$\{String\(o\.orderNo \|\| ''\)\.slice\(-4\)\}`;/);
  assert.match(source, /orderTime\.textContent = String\(o\.createdAt \|\| ''\)\.slice\(11, 16\);/);
  assert.match(source, /shop\.textContent = o\.shopName \|\| 'Shop';/);
  assert.match(source, /total\.textContent = `\$\{o\.totalAmount \|\| 0\} RSD`;/);
  assert.match(source, /status\.textContent = getAdminDispatchStatusCopy\(o\.status\);/);
  assert.match(source, /import \{[^}]*filterRiderDashboardOrders[^}]*getAdminDispatchStatusCopy[^}]*getRiderActionFlags[^}]*getRiderDispatchState[^}]*isRiderDeliveringOrder[^}]*readDispatchMetaFromRemarks[^}]*\} from '\.\.\/\.\.\/lib\/rider-dispatch\.ts';/);
  assert.match(source, /const canTake = rider\.status === 'available' && actionState\.canAccept && actionFlags\.canAccept;/);

  assert.doesNotMatch(source, /status\.textContent = o\.status;/);
  assert.match(source, /courierPhone: rider\.phone,/);
  assert.match(source, /courierName: rider\.name, courierPhone: rider\.phone/);

  assert.doesNotMatch(source, /order_no/);
  assert.doesNotMatch(source, /telegram_chat_id/);
  assert.doesNotMatch(source, /items_json/);
  assert.doesNotMatch(source, /table_info/);
  assert.doesNotMatch(source, /user_phone/);
  assert.doesNotMatch(source, /pickup_eta_minutes/);
  assert.doesNotMatch(source, /created_at/);
  assert.doesNotMatch(source, /shop_name/);
  assert.doesNotMatch(source, /total_amount/);
  assert.doesNotMatch(source, /courier_phone/);
  assert.doesNotMatch(source, /courier_name/);
});
